[workspace]
name = "similarity_search"
channels = ["conda-forge", "nvidia/label/cuda-12.6.3"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.10"
cuda-toolkit = { version = "12.*", channel = "nvidia/label/cuda-12.6.3" }
cudnn = "9.*"
huggingface_hub = "*"
ipywidgets = ">=8.1.8,<9"
jupyterlab = ">=4.5.7,<5"
scikit-learn = "*"

[pypi-dependencies]
# LINCC packages
lsdb-rubin = "*"
lsdb = { git = "https://github.com/astronomy-commons/lsdb.git", branch = "operations" }
hats = { git = "https://github.com/astronomy-commons/hats.git", branch = "main" }
nested-pandas = { git = "https://github.com/lincc-frameworks/nested-pandas.git", branch = "main" }

# Embedding conversion
light-curve = "*"
onnxruntime-gpu = "*"
